@startuml
title Quy trinh lam De cua Tuan

start
:Kiem tra va cai dat NFS;
:Kiem tra va cai dat PORTMAP hoac rpcbind;
:Nhap dia chi client va mang duoc phep;
:Export /usr/share cho mot client;
:Export /soft quyen rw cho ca mang;
:Khoi dong rpcbind va nfs-server;
:Nap lai bang export;
:Kiem tra NFS bang rpcinfo;
:Kiem tra PORTMAP bang rpcinfo;
:Thong ke loi va trang thai NFS Server;
:Liet ke filesystem dang mount;
:Xem danh sach export directory;
:Thong ke tai nguyen he thong theo user;
stop

@enduml
